# Generated by Django 5.2.7 on 2025-12-31 04:08

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_delete_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to=applications.models.cv_upload_path),
        ),
    ]
